server:
  port: 8080

spring:
  application:
    name: sistema-gestion-tareas

  datasource:
    url: jdbc:postgresql://localhost:5432/sistematareas
    username: postgres # Reemplaza por tu usuario real de Postgres
    password: hola123 # Reemplaza por tu contraseña real
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true